export {
  createSubmission,
  subscribeToArtistSubmissions,
  subscribeToSubmissions,
  subscribeToAllSubmissions,
  subscribeToSubmissionStats,
  getSubmissionsPaginated,
  updateSubmissionStatus,
  featureSubmission,
  updateFeaturedVisibility,
  updateFeaturedOrder,
  submitJudgeReview,
  getSubmissionById,
  getUserById,
  createUserDoc,
  subscribeToJudges,
  getJudgeByUserId,
  createJudgeRecord,
  deleteJudge,
} from "@/lib/firestore-live";
