import type { Judge, Submission } from "@/types";

const now = new Date();

export const MOCK_SUBMISSIONS: Submission[] = [
  {
    id: "sub-1",
    artistId: "artist-1",
    artistName: "Amara Soul",
    title: "Midnight Groove",
    videoLink: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    genre: "R&B",
    location: "Lagos, Nigeria",
    status: "featured",
    score: 9.2,
    judgeNotes: "Exceptional vocal range",
    featuredType: "FEATURED",
    featuredOrder: 1,
    featuredVisible: true,
    createdAt: new Date(now.getTime() - 86400000 * 2),
  },
  {
    id: "sub-2",
    artistId: "artist-2",
    artistName: "Kofi Beats",
    title: "Afro Sunrise",
    videoLink: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    genre: "Afropop",
    location: "Accra, Ghana",
    status: "featured",
    score: 8.7,
    judgeNotes: "Great energy on stage",
    featuredType: "TRENDING",
    featuredOrder: 2,
    featuredVisible: true,
    createdAt: new Date(now.getTime() - 86400000 * 3),
  },
  {
    id: "sub-3",
    artistId: "artist-3",
    artistName: "Grace Melody",
    title: "Heaven's Voice",
    videoLink: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    genre: "Gospel",
    location: "Nairobi, Kenya",
    status: "approved",
    score: 9.5,
    judgeNotes: "Powerful performance",
    featuredType: "TOP_PERFORMER",
    featuredOrder: 3,
    featuredVisible: true,
    createdAt: new Date(now.getTime() - 86400000 * 1),
  },
  {
    id: "sub-4",
    artistId: "artist-4",
    artistName: "Jay Flow",
    title: "Street Dreams",
    videoLink: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    genre: "Rap",
    location: "Johannesburg, SA",
    status: "pending",
    score: 0,
    judgeNotes: "",
    featuredType: null,
    createdAt: new Date(now.getTime() - 86400000 * 0.5),
  },
  {
    id: "sub-5",
    artistId: "artist-5",
    artistName: "Luna Star",
    title: "Pop Sensation",
    videoLink: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    genre: "Pop",
    location: "Cape Town, SA",
    status: "pending",
    score: 0,
    judgeNotes: "",
    featuredType: null,
    createdAt: new Date(now.getTime() - 86400000 * 0.25),
  },
  {
    id: "sub-6",
    artistId: "artist-6",
    artistName: "Pen Master",
    title: "Written in Stars",
    videoLink: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    genre: "Songwriting",
    location: "Kigali, Rwanda",
    status: "approved",
    score: 8.3,
    judgeNotes: "Creative lyrics",
    featuredType: null,
    createdAt: new Date(now.getTime() - 86400000 * 4),
  },
];

export const MOCK_JUDGES: Judge[] = [
  {
    id: "judge-1",
    userId: "user-judge-1",
    name: "Sarah Williams",
    genre: "R&B",
    assignedBy: "admin",
  },
  {
    id: "judge-2",
    userId: "user-judge-2",
    name: "David Okafor",
    genre: "Afropop",
    assignedBy: "admin",
  },
];
